### ISSUE TITLE
Help with sizing 

### ISSUE THREAD

**Issue by Michael-Aguirre-Merchan** [grzegorz103/ngx-chess-board#102]
Hi @grzegorz103 

I really liked your project, I'm trying to implement it right now, but I am having some problems to understand how can I change the size actively (like the demo, where you change the input number and the board just loads again with the new size). I would be really gratefully if you could explain that to me

**Comment by grzegorz103** [comment]
Hi @Michael-Aguirre-Merchan 

In the demo there is `[size]="size"` input in the `app.component.html` file. The `"size"` is a variable (it is placed in `app.component.ts` as `public size = 400;`). The html control where you have the size number (33 line in `app.component.html`) is bound to this variable with `[(ngModel)]="size"`. This means when you change the `size` variable's value with this html control, the board resizes correspondently, because this variable is passed to chess board component. I hope it is more clear now :)

**Comment by Michael-Aguirre-Merchan** [comment]
Ty
