### ISSUE TITLE
Freemode Functionality 

### ISSUE THREAD

**Issue by BenPearson95** [grzegorz103/ngx-chess-board#177]
Hi Grzegorz,

If I play a move as white with Freemode off, then turn Freemode on, and play another move, it seems that the move which is played next is registered or tracked by the game. This can mean that for example after the White move and the turning on of Freemode, you could move a Black piece once, then back to it's original square, and that would count as Blacks move, which then makes it whites turn again. 

Perhaps with Freemode on, the board could not track any moves / add them to the PGN, etc... To try and keep the board in a state where it was before Freemode was true?

Any issues or better solutions let me know!

Cheers,

**Comment by grzegorz103** [comment]
Hi. I think a workaround could be saving original pgn or fen when turning on the free mode, and setting it back when it gets turned off. Maybe in this way it would be possible to keep original state where it was before turning on. 
Generally as i remember, it always sets current player as opposite color to last move made. So when you have enabled free mode and moved black piece and you disable, then next move will be white, Even if you moved the piece back to its original field.
And for fen and pgn - it is tracked even with free mode on. Indeed it should be turned off then, because it makes no sense to track it with free mode. Ill try to fix it anytime.

Thank you and if you need anything let me know.

**Comment by BenPearson95** [comment]
Hey,

Thanks for your reply, some good alternatives I can think about. :) 

Cheers,
